### ISSUE TITLE
assert fails with slurm option

### ISSUE THREAD

**Issue by TomNicholas** [malramsay64/experi#37]
https://github.com/malramsay64/experi/blob/b4d953b77829b81a1e66a024b3301d1087f76371/src/experi/run.py#L190

This line should be 
```python
assert scheduler in ["shell", "pbs", "slurm"]
```

**Comment by malramsay64** [comment]
Thanks for picking that up. Feel free to raise any other issues you come across. 

Also if you do manage to get it to work it would be great to know.
